"""
Django settings for Linkin_Agency project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lu6k@^j3o53kkc89i8t1qbyu-7a@uptlz507=ednxziox3tmao'

# SECURITY WARNING: don't run with debug turned on in production!


SWITCH_ERROR=True




DEBUG = True
ALLOWED_HOSTS = []

SITE_ID=1






# Application definition

INSTALLED_APPS = [
    'Agency_action.apps.AgencyConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles','Agency_action.apps.AgencyActionConfig',
    'widget_tweaks','rosetta','parler'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Linkin_Agency.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['html'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
        
    },
]


SUIT_CONFIG = {
    'MENU': 
        {'label': 'Translations', 'icon':'icon-globe', 'models': (
            {'label': 'Pick catalog', 'url': '/admin/language/pick'},
            {'label': 'Translate', 'url': '/admin/language/'},
        )},
}







WSGI_APPLICATION = 'Linkin_Agency.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en'
LANGUAGES=[('en',_("English")),('ar',_("Arabic")),('du',_("Germany")),]


PARLER_LANGUAGES={
      None:(
            {'code':'en',},
            {'code':'ar',},
            {'code':'du',},
      ),
      'default':{
            'fallback':'en',
            'hide_untranslated': False,
      },

}
PARLER_DEFAULT_LANGUAGE_CODE = 'en'


LOCALE_PATHS=[os.path.join(BASE_DIR,'locale')]

print("YOUR LOCALE PATH DIR\n",LOCALE_PATHS)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True








MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_URL='media/'

print("YOUR MEDIA DIR\n",MEDIA_ROOT)





# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[BASE_DIR/'static']
#STATIC_ROOT=os.path.join(BASE_DIR,'static')


print("YOUR STATIC FILE PATHS DIR\n")


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL='/'
LOGOUT_REDIRECT_URL='/'
