# Generated by Django 5.0 on 2023-12-19 22:13

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sport_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Web_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Emp_modelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('emp_name', models.CharField(default='Ahmed hany', max_length=40, verbose_name='emp_name')),
                ('emp_img', models.ImageField(default='user.png', upload_to='emps of %d %M %Y', verbose_name='emp_img')),
                ('salary', models.PositiveIntegerField(default=3000, verbose_name='salary')),
                ('position', models.CharField(default='Sales', max_length=20, verbose_name='position')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_x', to='Agency_action.emp_model')),
            ],
            options={
                'verbose_name': 'emp_model Translation',
                'db_table': 'Agency_action_emp_model_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrintingTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('campagin_cost', models.CharField(choices=[("<img src='' alt='laser'>Laser", 'Laser'), ("<img src='' alt='Paper'>Paper", 'Paper'), ("<img src='' alt='Baner'>Baner", 'Baner'), ("<img src='' alt='Stuff'> Stuff", 'Stuff')], default=("<img src='' alt='laser'>Laser", 'Laser'), max_length=30, verbose_name='campagin_cost')),
                ('Printing_title', models.CharField(default='Printing title', max_length=40, verbose_name='title')),
                ('printing_model', models.ImageField(default='prints.jpg', upload_to='printings of %d %M %Y', verbose_name='printing_model')),
                ('bio', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Est consequuntur earum cupiditate nobis provident, amet voluptate molestias corrupti! Veniam.', max_length=400, verbose_name='bio')),
                ('price_per_item', models.FloatField(default=1.5, max_length=3000.0, verbose_name='price_per_item')),
                ('amount', models.PositiveSmallIntegerField(default=20, verbose_name='amount')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_x', to='Agency_action.printing')),
            ],
            options={
                'verbose_name': 'printing Translation',
                'db_table': 'Agency_action_printing_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service_providerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('service_name', models.CharField(default='Dodge challenger 2006', max_length=35, verbose_name='service_name')),
                ('service_info', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Est consequuntur earum cupiditate nobis provident, amet voluptate molestias corrupti! Veniam.', max_length=400, verbose_name='service_info')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_x', to='Agency_action.service_provider')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_by', to='Agency_action.emp_model')),
            ],
            options={
                'verbose_name': 'service_provider Translation',
                'db_table': 'Agency_action_service_provider_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Social_mediaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('post_name', models.CharField(default='Post title', max_length=40, verbose_name='post_name')),
                ('platform_type', models.CharField(choices=[("<img src='' alt='fb'>Facebook", 'Facebook'), ("<img src='' alt='insta'>Insta", 'Insta'), ("<img src='' alt='whats'>Whatsapp", 'Whatsapp')], default=("<img src='' alt='fb'>Facebook", 'Facebook'), max_length=350, verbose_name='platform_type')),
                ('url_hyperlink', models.URLField(max_length=350, verbose_name='url_hyperlink')),
                ('postgraph', models.ImageField(default='soc.jpg', upload_to='postgraphs in %d %M %Y', verbose_name='postgraph')),
                ('bio', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Est consequuntur earum cupiditate nobis provident, amet voluptate molestias corrupti! Veniam.', max_length=400, verbose_name='bio')),
                ('campagin_cost', models.PositiveIntegerField(default=3000, verbose_name='campagin_cost')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_x', to='Agency_action.social_media')),
            ],
            options={
                'verbose_name': 'social_media Translation',
                'db_table': 'Agency_action_social_media_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sport_carTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('website name', models.CharField(default='Dodge challenger 2006', max_length=35, verbose_name='car_name')),
                ('car photo', models.ImageField(default='car.jpg', upload_to='car photo of %d %MM %YYYY', verbose_name='car_poster')),
                ('bio', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Est consequuntur earum cupiditate nobis provident, amet voluptate molestias corrupti! Veniam.', max_length=400, verbose_name='bio')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_x', to='Agency_action.sport_car')),
            ],
            options={
                'verbose_name': 'sport_car Translation',
                'db_table': 'Agency_action_sport_car_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User_profileTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('client_img', models.ImageField(default='user.png', upload_to='client face of %d %M %Y', verbose_name='client_img')),
                ('client_name', models.CharField(default='Amir client', max_length=50, verbose_name='client_name')),
                ('phone_number', models.PositiveIntegerField(default=1094128969, verbose_name='phone_number')),
                ('contracted_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracted_by', to='Agency_action.emp_model')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_x', to='Agency_action.user_profile')),
            ],
            options={
                'verbose_name': 'user_profile Translation',
                'db_table': 'Agency_action_user_profile_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Web_siteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('website name', models.CharField(default='web site x', max_length=20, verbose_name='web_name')),
                ('web_type', models.CharField(choices=[("<img src='' alt='stat'>Static", 'Static'), ("<img src='' alt='Dyn'>Dynamic", 'Dynamic')], default=("<img src='' alt='stat'>Static", 'Static'), max_length=50, verbose_name='web_type')),
                ('logo', models.ImageField(default='web2.jpg', upload_to='website of %d %M %Y', verbose_name='logo')),
                ('url_hyperlink', models.URLField(max_length=90, verbose_name='url_hyperlink')),
                ('bio', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Est consequuntur earum cupiditate nobis provident, amet voluptate molestias corrupti! Veniam.', max_length=400, verbose_name='bio')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_x', to='Agency_action.web_site')),
            ],
            options={
                'verbose_name': 'web_site Translation',
                'db_table': 'Agency_action_web_site_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
