# Generated by Django 5.0 on 2023-12-19 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency_action', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printingtranslation',
            name='Printing_title',
        ),
        migrations.RemoveField(
            model_name='sport_cartranslation',
            name='car photo',
        ),
        migrations.RemoveField(
            model_name='sport_cartranslation',
            name='website name',
        ),
        migrations.RemoveField(
            model_name='web_sitetranslation',
            name='website name',
        ),
        migrations.AddField(
            model_name='printingtranslation',
            name='title',
            field=models.CharField(default='Printing title', max_length=40, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='sport_cartranslation',
            name='car_name',
            field=models.CharField(default='Dodge challenger 2006', max_length=35, verbose_name='car_name'),
        ),
        migrations.AddField(
            model_name='sport_cartranslation',
            name='car_poster',
            field=models.ImageField(default='car.jpg', upload_to='car photo of %d %MM %YYYY', verbose_name='car_poster'),
        ),
        migrations.AddField(
            model_name='user_profiletranslation',
            name='related_to_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to=settings.AUTH_USER_MODEL, verbose_name='related_to_user'),
        ),
        migrations.AddField(
            model_name='web_sitetranslation',
            name='web_name',
            field=models.CharField(default='web site x', max_length=20, verbose_name='web_name'),
        ),
    ]
