# Generated by Django 5.0 on 2023-12-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency_action', '0002_remove_printingtranslation_printing_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name': ''},
        ),
        migrations.AlterModelOptions(
            name='user_profiletranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': ' Translation'},
        ),
        migrations.RemoveField(
            model_name='user_profiletranslation',
            name='related_to_user',
        ),
        migrations.AlterField(
            model_name='service_providertranslation',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_by', to='Agency_action.emp_model'),
        ),
    ]
