# Generated by Django 5.0 on 2023-12-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency_action', '0003_alter_user_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingtranslation',
            name='web_type',
            field=models.CharField(choices=[("<img src='' alt='laser'>Laser", 'Laser'), ("<img src='' alt='Paper'>Paper", 'Paper'), ("<img src='' alt='Baner'>Baner", 'Baner'), ("<img src='' alt='Stuff'> Stuff", 'Stuff')], default=("<img src='' alt='laser'>Laser", 'Laser'), max_length=50, verbose_name='web_type'),
        ),
        migrations.AlterField(
            model_name='social_mediatranslation',
            name='url_hyperlink',
            field=models.URLField(default='https://www.facebook.com/groups/604256213502156/?hoisted_section_header_type=recently_seen&multi_permalinks=1432232637371172', max_length=350, verbose_name='url_hyperlink'),
        ),
        migrations.AlterField(
            model_name='web_sitetranslation',
            name='url_hyperlink',
            field=models.URLField(default='https://www.w3schools.com/', max_length=90, verbose_name='url_hyperlink'),
        ),
        migrations.AlterField(
            model_name='web_sitetranslation',
            name='web_type',
            field=models.CharField(choices=[('Static', 'Static'), ('Dynamic', 'Dynamic')], default=('Static', 'Static'), max_length=50, verbose_name='web_type'),
        ),
    ]
