# Generated by Django 5.0 on 2023-12-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency_action', '0004_printingtranslation_web_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printingtranslation',
            name='web_type',
        ),
        migrations.AddField(
            model_name='printingtranslation',
            name='print_type',
            field=models.CharField(choices=[("<img src='' alt='laser'>Laser", 'Laser'), ("<img src='' alt='Paper'>Paper", 'Paper'), ("<img src='' alt='Baner'>Baner", 'Baner'), ("<img src='' alt='Stuff'> Stuff", 'Stuff')], default=("<img src='' alt='laser'>Laser", 'Laser'), max_length=50, verbose_name='print_type'),
        ),
    ]
