# Generated by Django 5.0 on 2024-01-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency_action', '0005_remove_printingtranslation_web_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printing',
            options={'verbose_name': 'prints', 'verbose_name_plural': 'prints'},
        ),
        migrations.AlterModelOptions(
            name='printingtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'prints Translation'},
        ),
        migrations.AlterModelOptions(
            name='service_provider',
            options={'verbose_name': 'providers', 'verbose_name_plural': 'providers'},
        ),
        migrations.AlterModelOptions(
            name='service_providertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'providers Translation'},
        ),
        migrations.AlterModelOptions(
            name='social_media',
            options={'verbose_name': 'social_media', 'verbose_name_plural': 'social_media'},
        ),
        migrations.AlterModelOptions(
            name='sport_car',
            options={'verbose_name': 'cars', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterModelOptions(
            name='sport_cartranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'cars Translation'},
        ),
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name': 'user_profile', 'verbose_name_plural': 'user_profile'},
        ),
        migrations.AlterModelOptions(
            name='user_profiletranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'user_profile Translation'},
        ),
        migrations.AlterModelOptions(
            name='web_site',
            options={'verbose_name': 'web_sites', 'verbose_name_plural': 'web_sites'},
        ),
        migrations.AlterModelOptions(
            name='web_sitetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'web_sites Translation'},
        ),
        migrations.AlterField(
            model_name='printingtranslation',
            name='campagin_cost',
            field=models.CharField(choices=[('Laser', 'Laser'), ('Paper', 'Paper'), ('Baner', 'Baner'), (' Stuff', 'Stuff')], default=('Laser', 'Laser'), max_length=30, verbose_name='campagin_cost'),
        ),
        migrations.AlterField(
            model_name='printingtranslation',
            name='print_type',
            field=models.CharField(choices=[('Laser', 'Laser'), ('Paper', 'Paper'), ('Baner', 'Baner'), (' Stuff', 'Stuff')], default=('Laser', 'Laser'), max_length=50, verbose_name='print_type'),
        ),
        migrations.AlterField(
            model_name='social_mediatranslation',
            name='platform_type',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Insta', 'Insta'), ('Whatsapp', 'Whatsapp')], default=('Facebook', 'Facebook'), max_length=350, verbose_name='platform_type'),
        ),
        migrations.AlterField(
            model_name='social_mediatranslation',
            name='postgraph',
            field=models.ImageField(default='soc.jpg', upload_to='postgraphs_', verbose_name='postgraph'),
        ),
    ]
