# Generated by Django 5.0 on 2024-01-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency_action', '0006_alter_printing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp_model',
            options={'verbose_name': 'emp_profile', 'verbose_name_plural': 'emps_profile'},
        ),
        migrations.AlterModelOptions(
            name='emp_modeltranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'emp_profile Translation'},
        ),
        migrations.AlterModelOptions(
            name='printing',
            options={'ordering': ['pk'], 'verbose_name': 'prints', 'verbose_name_plural': 'prints'},
        ),
        migrations.AlterField(
            model_name='printingtranslation',
            name='campagin_cost',
            field=models.PositiveBigIntegerField(default=2000, verbose_name='campagin_cost'),
        ),
        migrations.AlterField(
            model_name='printingtranslation',
            name='price_per_item',
            field=models.FloatField(default=1.5, max_length=300.0, verbose_name='price_per_item'),
        ),
    ]
