# Generated by Django 5.0 on 2024-01-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency_action', '0007_alter_emp_model_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profiletranslation',
            name='contracted_with',
        ),
    ]
